
require "Init"
require "GameTask"
require "Skill"
require "Building.Building"
require "Building.City"
require "SettingUserInterface"
require "Message"
require "Form"
require "Application"
require "War.Command"
require "War.Enemy"
require "War.Troop"
require "War.TroopList"
require "War.Conscript"
require "OCR"